### ISSUE TITLE
baudcheck doesn't pay attention to SINGLESPEED

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Optiboot/optiboot#113] opened 2015-03-14 10:24 UTC
```
the SINGLESPEED option was added, but the routines that check for good baud 
rate generator values don't pay any attention to it.

```

Original issue reported on code.google.com by `wes...@gmail.com` on 14 Dec 2014 at 10:06

**Comment by WestfW** [comment] 2017-06-19 07:28
Duplicate of: https://github.com/Optiboot/optiboot/issues/81

**Closed by WestfW** 2017-06-19 07:28 UTC
Labels: auto-migrated, Duplicate, Priority-Medium, Type-Defect
